name: Upload to PyPI

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "src/cofi_espresso/_version.py"

jobs:
  # if_merged:
  #   if: ${{ (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || (github.event_name == 'workflow_dispatch') }}
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: |
  #       echo The PR was merged

  ######################## GENERATE PACKAGE SOURCE #####################
  gen_pkg_source:
    # needs: if_merged
    if: github.repository_owner == 'inlab-geo'
    name: Generate package source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install -r envs/requirements_test.txt
      
      - name: Build with pre and post validation
        run: |
          python utils/build_package/build_with_checks.py
          python -m pip install .

      - name: Deploy to esp_build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: esp_build
          FOLDER: _esp_build
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      
  tag_pkg_source:
    name: Tag package source
    needs: gen_pkg_source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout build branch
        uses: actions/checkout@v3
        with:
          ref: esp_build
      
      - name: Extract Release Version
        id: release_version
        working-directory: src/cofi_espresso
        run: |
          set -e
          python -c "import _version as v; print(v.__version__)"
          echo ::set-output name=version::$(python -c "import _version as v; print(v.__version__)")

      - name: Create release build tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git tag "v${{ steps.release_version.outputs.version }}-build"
          git push origin "v${{ steps.release_version.outputs.version }}-build"
        # uses: rickstaa/action-create-tag@v1.3.0
        # with:
        #   tag: "v${{ steps.release_version.outputs.version }}-build"
        #   force_push_tag: true


  ######################## SOURCE DISTRIBUTION #########################
  build_sdist:
    name: Build source distribution
    needs: gen_pkg_source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: esp_build
      
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up environment
        run: |
          $CONDA/bin/conda install scikit-build

      - name: Build and check sdist
        run: |
          $CONDA/bin/python setup.py sdist
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  ######################## BINARY DISTRIBUTION #########################
  # build_wheels:
  #   name: Build wheels on ${{ matrix.os }}
  #   needs: gen_pkg_source
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest, macos-latest]

  #   steps:
  #     - name: Symlink gfortran for macOS
  #       if: runner.os == 'macOS'
  #       run: |
  #         # make sure gfortran is available
  #         # https://github.com/actions/virtual-environments/issues/2524
  #         # https://github.com/cbg-ethz/dce/blob/master/.github/workflows/pkgdown.yaml
  #         sudo ln -s /usr/local/bin/gfortran-10 /usr/local/bin/gfortran
  #         sudo mkdir /usr/local/gfortran
  #         sudo ln -s /usr/local/Cellar/gcc@10/*/lib/gcc/10 /usr/local/gfortran/lib
  #         gfortran --version

  #     - name: Checkout repo
  #       uses: actions/checkout@v2

  #     - name: Build wheels
  #       uses: pypa/cibuildwheel@v2.3.1
  #       env:
  #         # CIBW_ARCHS_MACOS: x86_64 universal2
  #         CIBW_SKIP: pp* *-win32 *-manylinux_i686 *-musllinux_*
  #         CIBW_ARCHS_MACOS: x86_64 arm64
  #         CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
  #         CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: ""

  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         path: wheelhouse/*.whl

  ######################## UPLOAD TO PYPI #########################
  publish_pypi:
    name: Upload source distribution and wheels to PyPI
    # needs: [build_sdist, build_wheels]
    needs: [build_sdist]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract Release Version
        id: release_version
        working-directory: src/cofi_espresso
        run: |
          set -e
          python -c "import _version as v; print(v.__version__)"
          echo ::set-output name=version::$(python -c "import _version as v; print(v.__version__)")

      - name: Create release tag
        uses: rickstaa/action-create-tag@v1.3.0
        with:
          tag: "v${{ steps.release_version.outputs.version }}"
          force_push_tag: true

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          verbose: true
