name: Update pacakge source at esp_build branch

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - 'contrib/**'
      - 'src/**'
      - 'docs/**'
      - 'setup.py'
      - 'pyproject.toml'
  
jobs:
  ######################## GENERATE PACKAGE SOURCE #####################
  gen_pkg_source:
    name: Generate package source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install -r envs/requirements_test.txt
          python -m pip install .
      
      - name: Build with pre and post validation
        run: |
          python utils/build_package/build_with_checks.py
      
      - name: Deploy to esp_build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: esp_build
          FOLDER: _esp_build
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
